services:
  - type: web
    name: shadow-os
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r Requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0



